// Command assets-dist carries demo assets from the assets repository to the
// places that show them, then reports what changed.
//
// Targets:
//   - vscode-infinite-pm/media/demo/ — the GIFs the extension README embeds
//   - vscode-infinite-pm/README.md   — a "See it work" section between markers
//
// Only what a page ACTUALLY asks for. The extension README shows two recordings
// and links out for the rest; shipping all seven would put megabytes of GIF into
// the repository for scenarios nobody scrolls to. Which two is declared here,
// per target, and nothing else is copied.
//
// Nothing is drawn here. Every file is copied out of the assets repository,
// which is the only place recordings are produced; a distributor that generated
// its own would be a file nobody could regenerate and nothing documented.
//
// The README section is written between HTML comment markers. If they are
// missing the tool says where to put them and changes nothing — guessing at a
// place to splice into someone's README is how a distributor loses trust.
//
//	go run ./cmd-dev/assets-dist            # update + report
//	go run ./cmd-dev/assets-dist --check    # report only, exit 1 if stale
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// featured is what the extension README shows, in the order it shows them.
var featured = []struct{ scene, title string }{
	{"ipmt-buttons", "Preview a `.ipmt` file, beside the source or in its place"},
	{"embed-on-save", "Diagrams in Markdown: rendered as you type, written on save"},
}

const (
	markStart = "<!-- demo-assets:start -->"
	markEnd   = "<!-- demo-assets:end -->"
)

func main() {
	assets := flag.String("assets", "../vscode-infinite-pm-demo", "assets repository to copy from")
	ext := flag.String("ext", "../vscode-infinite-pm", "extension repository to copy into")
	url := flag.String("url", "https://github.com/infinite-pm/vscode-infinite-pm-demo",
		"where the README sends readers for the rest")
	check := flag.Bool("check", false, "report what would change and exit 1 if anything would")
	flag.Parse()

	assetsDir, extDir := abs(*assets), abs(*ext)
	for _, dir := range []string{assetsDir, extDir} {
		if _, err := os.Stat(dir); err != nil {
			fatalf("no repository at %s", dir)
		}
	}

	var changes []string
	changes = append(changes, copyGifs(assetsDir, extDir, *check)...)
	changed, err := updateReadme(extDir, *url, *check)
	if err != nil {
		// A missing marker pair is a message, not a crash: the README is left
		// exactly as it was and the operator is told what to add.
		fmt.Fprintln(os.Stderr, "assets-dist: "+err.Error())
	} else if changed {
		changes = append(changes, "README.md")
	}

	if len(changes) == 0 {
		fmt.Println("assets-dist: everything already up to date")
		return
	}
	verb := "updated"
	if *check {
		verb = "would update"
	}
	fmt.Printf("assets-dist: %s in %s\n", verb, extDir)
	for _, change := range changes {
		fmt.Printf("  %s\n", change)
	}
	if *check {
		os.Exit(1)
	}
	fmt.Println("\nReview and commit in the extension repository.")
}

func copyGifs(assetsDir, extDir string, check bool) []string {
	mediaDir := filepath.Join(extDir, "media", "demo")
	if !check {
		if err := os.MkdirAll(mediaDir, 0o755); err != nil {
			fatalf("%v", err)
		}
	}

	var changes []string
	for _, f := range featured {
		from := filepath.Join(assetsDir, "video", f.scene+".gif")
		to := filepath.Join(mediaDir, f.scene+".gif")
		want, err := os.ReadFile(from)
		if err != nil {
			fatalf("%s is missing -- run 'make demo && make publish' first", from)
		}
		if have, err := os.ReadFile(to); err == nil && bytes.Equal(have, want) {
			continue
		}
		changes = append(changes, filepath.Join("media", "demo", f.scene+".gif"))
		if !check {
			if err := os.WriteFile(to, want, 0o644); err != nil {
				fatalf("%v", err)
			}
		}
	}
	return changes
}

func updateReadme(extDir, url string, check bool) (bool, error) {
	path := filepath.Join(extDir, "README.md")
	current, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	start := bytes.Index(current, []byte(markStart))
	end := bytes.Index(current, []byte(markEnd))
	if start < 0 || end < start {
		return false, fmt.Errorf("%s has no %s / %s pair.\n"+
			"Add them where the section belongs and run again; nothing was written to the README.",
			path, markStart, markEnd)
	}

	var b strings.Builder
	b.WriteString(markStart + "\n")
	b.WriteString("<!-- Generated by vscode-infinite-pm-dev/cmd-dev/assets-dist. Do not edit by hand. -->\n\n")
	b.WriteString("## See it work\n\n")
	for _, f := range featured {
		fmt.Fprintf(&b, "### %s\n\n![%s](media/demo/%s.gif)\n\n", f.title, f.scene, f.scene)
	}
	fmt.Fprintf(&b, "More scenarios — live refresh, includes, diagnostics — with step-by-step stills:\n[%s](%s).\n\n",
		filepath.Base(url), url)
	b.WriteString(markEnd)

	next := append(append(append([]byte{}, current[:start]...), b.String()...), current[end+len(markEnd):]...)
	if bytes.Equal(next, current) {
		return false, nil
	}
	if !check {
		if err := os.WriteFile(path, next, 0o644); err != nil {
			return false, err
		}
	}
	return true, nil
}

func abs(path string) string {
	resolved, err := filepath.Abs(path)
	if err != nil {
		return path
	}
	return resolved
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "assets-dist: "+format+"\n", args...)
	os.Exit(2)
}
